# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE UI will override any settings in this file.

# Enable AndroidX
android.useAndroidX=true

# JVM memory and GC settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style
kotlin.code.style=official

# Enable KSP & parallel build
org.gradle.parallel=true
org.gradle.caching=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
